name: Auto Pin Repos

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  pin-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @octokit/graphql @octokit/rest node-fetch

      - name: Run Script to Pin Repos
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          node pin-repos.js
